spring:
  server:
    port: 8001
  data:
    mongodb:
      database: WorkOrderServiceDB
      uri: your_mongodb_uri
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MongoDBDialect
  graphql:
    path: /graphql
    schema:
      fileExtensions: .graphqls, .gqls
      printer:
        enabled: true
    graphiql:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: host.docker.internal:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
#json
spring.jackson:
  date-format: "yyyy-MM-dd HH:mm:ss"
  default-property-inclusion: NON_NULL

#log
logging:
  config: "file:conf/logback-spring.xml"

workorderServer:
  baseUrl: http://host.docker.internal:${spring.server.port}
  kafkaTopic: "work-order-events"
  workorderCreated: "workorderCreated"
  workorderChanged: "workorderChanged"
  workorderDeleted: "workorderDeleted"
